name: Linux CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7","3.8","3.9"]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[all]
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Run IR tests
        run: |
          pytest -s --cov PrimeQA --cov-config .coveragerc tests/primeqa/ir
      - name: Run MRC tests Part 1 (processors)
        run: |
          pytest -s --cov PrimeQA --cov-config .coveragerc tests/primeqa/mrc/processors
      - name: Run MRC tests Part 2 (all except processors)
        run: |
          pytest -s --cov PrimeQA --cov-config .coveragerc --ignore tests/primeqa/mrc/processors tests/primeqa/mrc

      - run: echo "🍏 This job's status is ${{ job.status }}."
